CREATE DATABASE IF NOT EXISTS goann;

USE goann;

CREATE TABLE player (
  id SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
  age SMALLINT UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE gene (
  player SMALLINT UNSIGNED NOT NULL REFERENCES player (id) ON DELETE CASCADE,
  id MEDIUMINT UNSIGNED NOT NULL,
  value SMALLINT NOT NULL DEFAULT 0 COMMENT 'represents real number in [-1,1] with 4 decimal places',
  CONSTRAINT PRIMARY KEY (player, id)
);

CREATE TABLE game (
  white SMALLINT UNSIGNED NOT NULL REFERENCES player (id) ON DELETE CASCADE,
  black SMALLINT UNSIGNED NOT NULL REFERENCES player (id) ON DELETE CASCADE,
  winner ENUM ('WHITE', 'DRAW', 'BLACK') NOT NULL,
  CONSTRAINT PRIMARY KEY (white, black)
);

CREATE TABLE action (
  action_type ENUM ('WHITE', 'BLACK', 'REMOVE') NOT NULL,
  place SMALLINT UNSIGNED NOT NULL,
  action_order SMALLINT UNSIGNED NOT NULL,
  white SMALLINT UNSIGNED NOT NULL,
  black SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT FOREIGN KEY (white, black) REFERENCES game (white, black) ON DELETE CASCADE
);

